export type ApiEndpointClassification =
  | "PUBLIC"
  | "AUTHENTICATED"
  | "ROLE_RESTRICTED"
  | "ADMIN"
  | "INTERNAL";

export type ApiRateLimitProfile =
  | "none"
  | "auth"
  | "api"
  | "mutation"
  | "spatial";

export interface ApiEndpointPolicy {
  allowedRequestHeaders: readonly string[];
  classification: ApiEndpointClassification;
  cors: "allowlist";
  method: "GET" | "PATCH" | "POST" | "PUT" | "DELETE";
  path: string;
  purpose: string;
  rateLimit: ApiRateLimitProfile;
  role: "NONE" | "AUTHENTICATED" | "ADMIN";
}

const CONTENT_HEADERS = [
  "content-type",
  "x-request-id",
] as const;

const AUTH_HEADERS = [
  "authorization",
  "x-request-id",
] as const;

const AUTH_CONTENT_HEADERS = [
  "authorization",
  "content-type",
  "x-request-id",
] as const;

const AUTH_MERCHANT_HEADERS = [
  "authorization",
  "content-type",
  "x-request-id",
  "x-getra-merchant-id",
  "x-merchant-id",
] as const;

const AUTH_MERCHANT_GET_HEADERS = [
  "authorization",
  "x-request-id",
  "x-getra-merchant-id",
  "x-merchant-id",
] as const;

export const API_ENDPOINT_POLICIES: readonly ApiEndpointPolicy[] = [
  // Public
  {
    method: "GET",
    path: "/api/health",
    classification: "PUBLIC",
    role: "NONE",
    rateLimit: "none",
    cors: "allowlist",
    allowedRequestHeaders: ["x-request-id"],
    purpose: "Readiness and database connectivity",
  },
  {
    method: "POST",
    path: "/api/auth/login",
    classification: "PUBLIC",
    role: "NONE",
    rateLimit: "auth",
    cors: "allowlist",
    allowedRequestHeaders: CONTENT_HEADERS,
    purpose: "Supabase bearer-token login",
  },
  {
    method: "POST",
    path: "/api/auth/register",
    classification: "PUBLIC",
    role: "NONE",
    rateLimit: "auth",
    cors: "allowlist",
    allowedRequestHeaders: CONTENT_HEADERS,
    purpose: "Public non-admin registration",
  },
  {
    method: "POST",
    path: "/api/ai/ask",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Grounded GETRA AI question answering",
  },

  // Auth
  {
    method: "POST",
    path: "/api/auth/logout",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Acknowledge stateless client logout",
  },
  {
    method: "GET",
    path: "/api/auth/me",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Authenticated user and profile",
  },
  {
    method: "GET",
    path: "/api/contextual-observations",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "spatial",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read safe viewport-bounded Mission contextual observations",
  },
  {
    method: "GET",
    path: "/api/accessibility/evidence",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "spatial",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read safe viewport-bounded accessibility evidence observations",
  },
  {
    method: "GET",
    path: "/api/accessibility/evidence/[evidenceId]",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read safe accessibility evidence detail and candidate network relation",
  },
  {
    method: "GET",
    path: "/api/accessibility/need",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "spatial",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read viewport accessibility evidence aggregation without route penalties",
  },
  {
    method: "GET",
    path: "/api/internal/routing/graph-health",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "spatial",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read aggregate pedestrian graph health diagnostics",
  },

  // Community
  {
    method: "GET",
    path: "/api/community/feed",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read GETRA Community feed with public location projection",
  },
  {
    method: "GET",
    path: "/api/community/contributions",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read own Community accessibility contribution history and points summary",
  },
  {
    method: "POST",
    path: "/api/community/contributions",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Create a pending Community accessibility contribution",
  },
  {
    method: "GET",
    path: "/api/community/contributions/[contributionId]",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read own pending Community accessibility contribution",
  },
  {
    method: "GET",
    path: "/api/community/contributions/merchants",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Search canonical merchants for Community correction contributions",
  },
  {
    method: "GET",
    path: "/api/community/contributions/map",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read approved-only Community contribution map projection",
  },
  {
    method: "POST",
    path: "/api/community/posts",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Create a GETRA Community post with optional location and photo",
  },
  {
    method: "GET",
    path: "/api/community/cultural-map",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read GETRA Community findings for Cultural Map bbox",
  },
  {
    method: "GET",
    path: "/api/community/requests",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read active structured commuter requests",
  },
  {
    method: "POST",
    path: "/api/community/requests",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Create structured commuter request",
  },
  {
    method: "GET",
    path: "/api/community/requests/[requestId]",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read structured commuter request detail",
  },
  {
    method: "GET",
    path: "/api/community/requests/signals",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read deterministic Community Demand Signals",
  },
  {
    method: "GET",
    path: "/api/community/requests/signals/[signalId]",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read deterministic Community Demand Signal detail",
  },
  {
    method: "GET",
    path: "/api/community/requests/signals/[signalId]/responses",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read UMKM responses for a Community Demand Signal",
  },
  {
    method: "POST",
    path: "/api/community/requests/signals/[signalId]/responses",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Create or update verified merchant response for a Community Demand Signal",
  },
  {
    method: "GET",
    path: "/api/community/posts/[postId]",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read GETRA Community post detail thread header",
  },
  {
    method: "GET",
    path: "/api/community/posts/[postId]/comments",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read GETRA Community post comments and replies",
  },
  {
    method: "POST",
    path: "/api/community/posts/[postId]/comments",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Create GETRA Community comment or bounded reply",
  },
  {
    method: "PUT",
    path: "/api/community/posts/[postId]/reactions/[reactionType]",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Add idempotent GETRA Community post reaction",
  },
  {
    method: "DELETE",
    path: "/api/community/posts/[postId]/reactions/[reactionType]",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Remove own GETRA Community post reaction",
  },
  {
    method: "GET",
    path: "/api/community/notifications",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read scoped GETRA Community notifications",
  },
  {
    method: "PATCH",
    path: "/api/community/notifications/[notificationId]/read",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Mark one scoped GETRA Community notification read",
  },
  {
    method: "PATCH",
    path: "/api/community/notifications/read-all",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Mark scoped GETRA Community notifications read",
  },
  {
    method: "POST",
    path: "/api/community/reports",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Create a GETRA Community moderation report",
  },
  {
    method: "GET",
    path: "/api/community/reputation/[userId]",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read derived GETRA Community reputation metrics",
  },
  {
    method: "GET",
    path: "/api/community/users/[userId]",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read safe Community user profile and relationship state",
  },
  {
    method: "GET",
    path: "/api/community/friends",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read scoped Community friends and friend requests",
  },
  {
    method: "POST",
    path: "/api/community/friends/requests",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Send consent-based Community friend request",
  },
  {
    method: "PATCH",
    path: "/api/community/friends/[friendshipId]",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Accept, decline, cancel, or unfriend scoped Community friendship",
  },

  // Profile
  {
    method: "GET",
    path: "/api/profile",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read own profile through RLS",
  },
  {
    method: "PATCH",
    path: "/api/profile",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Update own profile through RLS",
  },
  {
    method: "POST",
    path: "/api/profile/avatar",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Upload own circular profile avatar to Supabase Storage",
  },
  {
    method: "GET",
    path: "/api/profiles",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "List safe public profile cards for authenticated users",
  },
  {
    method: "GET",
    path: "/api/profiles/[id]",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read a safe public profile by id for authenticated users",
  },

  // Onboarding
  {
    method: "GET",
    path: "/api/onboarding",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Get onboarding status and modes",
  },
  {
    method: "POST",
    path: "/api/onboarding",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Submit onboarding modes",
  },

  // Spatial
  {
    method: "POST",
    path: "/api/spatial/distance",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "spatial",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "PostGIS geography distance",
  },
  {
    method: "GET",
    path: "/api/spatial/nearby",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "spatial",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Bounded PostGIS proximity query",
  },
  {
    method: "GET",
    path: "/api/spatial/bbox",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "spatial",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Bounded PostGIS bbox query",
  },

  // Admin
  {
    method: "POST",
    path: "/api/admin/ingestion/jobs",
    classification: "ADMIN",
    role: "ADMIN",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Create ingestion job",
  },
  {
    method: "POST",
    path: "/api/admin/ingestion/run",
    classification: "ADMIN",
    role: "ADMIN",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Run ingestion job",
  },
  {
    method: "POST",
    path: "/api/spatial/service-area",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "spatial",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Calculate bounded pedestrian network service area",
  },
  {
    method: "POST",
    path: "/api/admin/mapid/mission-sync",
    classification: "ADMIN",
    role: "ADMIN",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Run server-side MAPID Mission data synchronization",
  },
  {
    method: "GET",
    path: "/api/admin/mission/sync",
    classification: "ADMIN",
    role: "ADMIN",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read safe MAPID Mission synchronization status",
  },
  {
    method: "POST",
    path: "/api/admin/mission/sync",
    classification: "ADMIN",
    role: "ADMIN",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Run a canonical MAPID Mission source synchronization",
  },
  {
    method: "POST",
    path: "/api/admin/accessibility/evidence/[evidenceId]/review",
    classification: "ADMIN",
    role: "ADMIN",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Review accessibility evidence status and candidate pedestrian relation",
  },
  {
    method: "GET",
    path: "/api/admin/merchant-reconciliation",
    classification: "ADMIN",
    role: "ADMIN",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read Premium and Menu Go merchant reconciliation status",
  },
  {
    method: "POST",
    path: "/api/admin/merchant-reconciliation",
    classification: "ADMIN",
    role: "ADMIN",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Run deterministic Premium and Menu Go merchant reconciliation",
  },
  {
    method: "POST",
    path: "/api/admin/map-import/preview",
    classification: "ADMIN",
    role: "ADMIN",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Preview temporary admin map import from JSON or public API URL",
  },
  {
    method: "POST",
    path: "/api/admin/map-import/commit",
    classification: "ADMIN",
    role: "ADMIN",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Persist a validated admin map import into canonical spatial tables",
  },
  {
    method: "DELETE",
    path: "/api/admin/map-import/layers/[id]",
    classification: "ADMIN",
    role: "ADMIN",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Delete a persisted admin-imported map layer from canonical spatial tables",
  },
  {
    method: "PATCH",
    path: "/api/admin/map-import/layers/[id]",
    classification: "ADMIN",
    role: "ADMIN",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Update metadata for a persisted admin-imported map layer",
  },
  {
    method: "GET",
    path: "/api/admin/community/reports",
    classification: "ADMIN",
    role: "ADMIN",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read GETRA Community moderation report queue",
  },
  {
    method: "PATCH",
    path: "/api/admin/community/reports/[reportId]",
    classification: "ADMIN",
    role: "ADMIN",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Apply GETRA Community moderation action",
  },
  {
    method: "GET",
    path: "/api/admin/community/contributions",
    classification: "ADMIN",
    role: "ADMIN",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read GETRA Community contribution moderation queue",
  },
  {
    method: "GET",
    path: "/api/admin/community/contributions/[contributionId]",
    classification: "ADMIN",
    role: "ADMIN",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read safe GETRA Community contribution moderation detail",
  },
  {
    method: "POST",
    path: "/api/admin/community/contributions/[contributionId]/confirm",
    classification: "ADMIN",
    role: "ADMIN",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Approve a pending GETRA Community contribution",
  },
  {
    method: "POST",
    path: "/api/admin/community/contributions/[contributionId]/reject",
    classification: "ADMIN",
    role: "ADMIN",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Reject a pending GETRA Community contribution with a safe reason",
  },
  {
    method: "GET",
    path: "/api/admin/community/analytics",
    classification: "ADMIN",
    role: "ADMIN",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read aggregate GETRA Community operational analytics",
  },

  {
    method: "GET",
    path: "/api/map-import/layers",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read persisted admin-imported map layers",
  },

  // Existing compatibility endpoints
  {
    method: "GET",
    path: "/api/internal/poi/nearby",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Nearby POI compatibility query",
  },
  {
    method: "GET",
    path: "/api/internal/umkm/nearby",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Nearby legacy UMKM compatibility query",
  },
  {
    method: "POST",
    path: "/api/internal/routing/walking",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "spatial",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Pedestrian walking route calculation",
  },
  {
    method: "POST",
    path: "/api/routing",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "spatial",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Pedestrian routing from origin to destination coordinates",
  },
  {
    method: "POST",
    path: "/api/transport/nearest",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "spatial",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Nearest transport nodes around a coordinate",
  },
  {
    method: "GET",
    path: "/api/system/foundation",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "GETRA foundation system information",
  },
  {
    method: "GET",
    path: "/api/mapid/food-beverage",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "MAPID food and beverage layer proxy",
  },
  {
    method: "GET",
    path: "/api/mapid/mission-observations",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read normalized MAPID Mission observations through GETRA contract",
  },
  {
    method: "GET",
    path: "/api/merchants/canonical",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read reconciled canonical merchants without duplicate source records",
  },
  {
    method: "GET",
    path: "/api/analytics/demand",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "spatial",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read aggregate GETRA observed demand signals",
  },
  {
    method: "GET",
    path: "/api/umkm/intelligence",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "spatial",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read owner-authorized canonical merchant intelligence aggregates",
  },
  {
    method: "POST",
    path: "/api/umkm/intelligence/copilot",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Explain owner-authorized merchant intelligence facts",
  },
  {
    method: "GET",
    path: "/api/analytics/retail-gap",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "spatial",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read aggregate represented-supply and Retail Gap signals",
  },
  {
    method: "POST",
    path: "/api/analytics/interpretation",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Explain server-computed demand intelligence facts",
  },
  {
    method: "GET",
    path: "/api/business-space/candidates",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "spatial",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read bounded Properti Go business-space candidates",
  },
  {
    method: "GET",
    path: "/api/business-space/candidates/[candidateId]",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "spatial",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read one Properti Go business-space candidate context",
  },
  {
    method: "POST",
    path: "/api/business-space/compare",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "spatial",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Compare bounded Properti Go business-space candidates",
  },
  {
    method: "POST",
    path: "/api/business-space/insight",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Explain grounded business-space candidate comparison evidence",
  },
  {
    method: "GET",
    path: "/api/regions",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read selected trusted administrative boundaries as safe GeoJSON",
  },
  {
    method: "GET",
    path: "/api/merchants/[id]/ownership",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Read merchant ownership state for authenticated user",
  },
  {
    method: "POST",
    path: "/api/merchants/[id]/ownership",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Submit a pending merchant ownership claim for review",
  },
  {
    method: "GET",
    path: "/api/umkm/advertising/my-merchants",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_MERCHANT_GET_HEADERS,
    purpose: "List owned and claimable merchants for UMKM user",
  },
  {
    method: "GET",
    path: "/api/umkm/advertising/eligibility",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_MERCHANT_GET_HEADERS,
    purpose: "Read UMKM advertising eligibility for authenticated user",
  },
  {
    method: "GET",
    path: "/api/umkm/advertising/campaigns",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_MERCHANT_GET_HEADERS,
    purpose: "List UMKM advertising campaigns for an owned merchant",
  },
  {
    method: "POST",
    path: "/api/umkm/advertising/campaigns",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_MERCHANT_HEADERS,
    purpose: "Create UMKM advertising campaign for an owned merchant",
  },
  {
    method: "GET",
    path: "/api/umkm/advertising/campaigns/[id]",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_MERCHANT_GET_HEADERS,
    purpose: "Read an owned UMKM advertising campaign",
  },
  {
    method: "PATCH",
    path: "/api/umkm/advertising/campaigns/[id]",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_MERCHANT_HEADERS,
    purpose: "Update an owned UMKM advertising campaign",
  },
  {
    method: "POST",
    path: "/api/umkm/advertising/campaigns/[id]/cancel",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_MERCHANT_HEADERS,
    purpose: "Cancel an owned UMKM advertising campaign",
  },
  {
    method: "GET",
    path: "/api/umkm/advertising/campaigns/[id]/creatives",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_MERCHANT_GET_HEADERS,
    purpose: "List campaign creatives",
  },
  {
    method: "POST",
    path: "/api/umkm/advertising/campaigns/[id]/creatives",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_MERCHANT_HEADERS,
    purpose: "Create campaign creative",
  },
  {
    method: "GET",
    path: "/api/umkm/advertising/campaigns/[id]/creatives/[creativeId]",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_MERCHANT_GET_HEADERS,
    purpose: "Read campaign creative",
  },
  {
    method: "PATCH",
    path: "/api/umkm/advertising/campaigns/[id]/creatives/[creativeId]",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_MERCHANT_HEADERS,
    purpose: "Update campaign creative",
  },
  {
    method: "POST",
    path: "/api/umkm/advertising/campaigns/[id]/creatives/[creativeId]/ready",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_MERCHANT_HEADERS,
    purpose: "Mark campaign creative ready",
  },
  {
    method: "POST",
    path: "/api/umkm/advertising/campaigns/[id]/creatives/[creativeId]/media",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_MERCHANT_HEADERS,
    purpose: "Upload campaign creative media",
  },
  {
    method: "GET",
    path: "/api/umkm/advertising/campaigns/[id]/targeting",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_MERCHANT_GET_HEADERS,
    purpose: "Read campaign spatial targeting",
  },
  {
    method: "PUT",
    path: "/api/umkm/advertising/campaigns/[id]/targeting",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_MERCHANT_HEADERS,
    purpose: "Update campaign spatial targeting",
  },
  {
    method: "GET",
    path: "/api/umkm/advertising/campaigns/[id]/lifecycle",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_MERCHANT_GET_HEADERS,
    purpose: "Read campaign lifecycle state and readiness",
  },
  {
    method: "PUT",
    path: "/api/umkm/advertising/campaigns/[id]/schedule",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_MERCHANT_HEADERS,
    purpose: "Update campaign schedule",
  },
  {
    method: "POST",
    path: "/api/umkm/advertising/campaigns/[id]/pause",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_MERCHANT_HEADERS,
    purpose: "Pause campaign",
  },
  {
    method: "POST",
    path: "/api/umkm/advertising/campaigns/[id]/resume",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_MERCHANT_HEADERS,
    purpose: "Resume campaign",
  },
  {
    method: "POST",
    path: "/api/umkm/advertising/campaigns/[id]/serving-preview",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_MERCHANT_HEADERS,
    purpose: "Owner preview campaign serving eligibility",
  },
  {
    method: "GET",
    path: "/api/advertising/placements/sponsored-pins",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Get eligible sponsored pin placement candidates for a spatial context",
  },
  {
    method: "GET",
    path: "/api/advertising/placements/contextual-banner",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Get eligible contextual promotional banner for a spatial/search context",
  },
  {
    method: "GET",
    path: "/api/merchants/[id]/advertising/profile-poster",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Get eligible profile promotion poster for a merchant profile",
  },
  {
    method: "POST",
    path: "/api/advertising/events",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Record validated campaign interaction event (append-only)",
  },

  // Fair Discovery
  {
    method: "GET",
    path: "/api/discovery",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Fair Discovery search and exploration for commuters",
  },
  {
    method: "POST",
    path: "/api/discovery",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Fair Discovery search query with body filters",
  },

  // Study areas
  {
    method: "GET",
    path: "/api/v1/study-areas",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "List study areas",
  },
  {
    method: "GET",
    path: "/api/v1/study-areas/[id]",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Get study area",
  },

  // Transport
  {
    method: "GET",
    path: "/api/v1/transport/nodes",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "List transport nodes",
  },
  {
    method: "GET",
    path: "/api/v1/transport/corridors",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "List transport corridors",
  },

  // UMKM Workspace & Submissions & Analytics (Phase 11)
  {
    method: "GET",
    path: "/api/umkm/workspace",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Get UMKM workspace summary",
  },
  {
    method: "GET",
    path: "/api/umkm/merchant-submissions",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "List user merchant submissions",
  },
  {
    method: "POST",
    path: "/api/umkm/merchant-submissions",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Create draft merchant submission",
  },
  {
    method: "GET",
    path: "/api/umkm/merchant-submissions/[id]",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Get merchant submission detail",
  },
  {
    method: "PATCH",
    path: "/api/umkm/merchant-submissions/[id]",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Update draft merchant submission",
  },
  {
    method: "POST",
    path: "/api/umkm/merchant-submissions/[id]/submit",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Submit draft merchant submission for review",
  },
  {
    method: "POST",
    path: "/api/umkm/merchant-submissions/[id]/cancel",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Cancel pending merchant submission",
  },
  {
    method: "GET",
    path: "/api/admin/merchant-submissions",
    classification: "ADMIN",
    role: "ADMIN",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Admin list pending merchant submissions",
  },
  {
    method: "POST",
    path: "/api/admin/merchant-submissions/[id]/approve",
    classification: "ADMIN",
    role: "ADMIN",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Admin approve merchant submission",
  },
  {
    method: "POST",
    path: "/api/admin/merchant-submissions/[id]/reject",
    classification: "ADMIN",
    role: "ADMIN",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Admin reject merchant submission",
  },
  {
    method: "GET",
    path: "/api/umkm/advertising/campaigns/[id]/analytics",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Get campaign interaction analytics aggregate",
  },
  {
    method: "POST",
    path: "/api/umkm/advertising/campaigns/[id]/payment/checkout",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Create Midtrans Sandbox Snap checkout token for advertising campaign",
  },
  {
    method: "GET",
    path: "/api/umkm/advertising/campaigns/[id]/payment",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "api",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_HEADERS,
    purpose: "Get current payment order status for advertising campaign",
  },
  {
    method: "POST",
    path: "/api/umkm/advertising/campaigns/[id]/payment/refresh",
    classification: "AUTHENTICATED",
    role: "AUTHENTICATED",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: AUTH_CONTENT_HEADERS,
    purpose: "Refresh and verify authoritative payment status from Midtrans for campaign",
  },
  {
    method: "POST",
    path: "/api/payments/midtrans/notification",
    classification: "PUBLIC",
    role: "NONE",
    rateLimit: "mutation",
    cors: "allowlist",
    allowedRequestHeaders: CONTENT_HEADERS,
    purpose: "External Midtrans HTTP notification webhook with signature verification",
  },
] as const;


export function findApiEndpointPolicy(
  path: string,
  method: string,
): ApiEndpointPolicy | undefined {
  return API_ENDPOINT_POLICIES.find(
    (policy) =>
      policy.path === path &&
      policy.method === method.toUpperCase(),
  );
}

export function getAllowedMethodsForPath(
  path: string,
): readonly string[] {
  return API_ENDPOINT_POLICIES
    .filter((policy) => policy.path === path)
    .map((policy) => policy.method);
};
