export const MAX_SPONSORED_RESULTS_PER_DISCOVERY = 1;

export const DEFAULT_DISCOVERY_RADIUS_METERS = 2000;

export const DEFAULT_DISCOVERY_LIMIT = 20;

export const AVERAGE_WALKING_SPEED_METERS_PER_MINUTE = 80; // ~4.8 km/h

export const HIDDEN_GEM_MIN_DATA_QUALITY_SCORE = 80;
