export const COMMUNITY_CONTRIBUTION_REPORT_TYPES = [
  "SIDEWALK_OBSTRUCTION",
  "RAMP_OR_GUIDING_BLOCK",
  "CROSSING",
  "MERCHANT_LOCATION_CHANGED",
  "MERCHANT_PRICE_CHANGED",
  "MERCHANT_HOURS_CHANGED",
] as const;

export const COMMUNITY_CONTRIBUTION_STATUSES = [
  "PENDING",
  "APPROVED",
  "REJECTED",
] as const;

export const COMMUNITY_CONTRIBUTION_REJECTION_REASONS = [
  "DUPLICATE",
  "INSUFFICIENT_INFORMATION",
  "INVALID_LOCATION",
  "INVALID_TARGET",
  "OUTDATED_INFORMATION",
  "OTHER",
] as const;

export const COMMUNITY_CONTRIBUTION_FACILITY_TYPES = [
  "RAMP",
  "GUIDING_BLOCK",
] as const;

export const COMMUNITY_CONTRIBUTION_DETAILS_MAX_LENGTH = 500;
export const COMMUNITY_CONTRIBUTION_PRICE_LEVEL_MAX_LENGTH = 64;
export const COMMUNITY_CONTRIBUTION_HOURS_KEY_MAX_LENGTH = 32;
export const COMMUNITY_CONTRIBUTION_HOURS_VALUE_MAX_LENGTH = 128;
export const COMMUNITY_CONTRIBUTION_HOURS_MAX_ENTRIES = 14;
