export const COMMUNITY_POST_MAX_LENGTH = 500;
export const COMMUNITY_COMMENT_MAX_LENGTH = 500;
export const COMMUNITY_FEED_DEFAULT_LIMIT = 20;
export const COMMUNITY_FEED_MAX_LIMIT = 50;
export const COMMUNITY_COMMENT_DEFAULT_LIMIT = 20;
export const COMMUNITY_COMMENT_MAX_LIMIT = 50;
export const COMMUNITY_LOCATION_APPROXIMATE_GRID_DEGREES = 0.001;
export const COMMUNITY_LOCATION_MAX_ACCURACY_M = 100000;
export const COMMUNITY_MEDIA_BUCKET = "community-media";
export const COMMUNITY_PHOTO_MAX_INPUT_BYTES = 10 * 1024 * 1024;
export const COMMUNITY_PHOTO_MAX_OUTPUT_BYTES = 10 * 1024 * 1024;
export const COMMUNITY_PHOTO_MAX_DIMENSION_PX = 2048;
export const COMMUNITY_PHOTO_MAX_INPUT_PIXELS = 25_000_000;
export const COMMUNITY_PHOTO_SIGNED_URL_SECONDS = 10 * 60;
export const COMMUNITY_PHOTO_OUTPUT_MIME_TYPE = "image/webp";
export const COMMUNITY_REACTION_TYPES = [
  "HELPFUL",
  "INTERESTING",
  "CONFIRMED",
] as const;
export const COMMUNITY_POST_TYPES = ["GENERAL", "FINDING"] as const;
export const COMMUNITY_FINDING_CATEGORIES = [
  "LEGENDARY_EATERY",
  "LOCAL_FOOD",
  "CRAFT_CENTER",
  "LANDMARK",
  "LOCAL_HISTORY",
  "COMMUNITY_ACTIVITY",
] as const;
export const COMMUNITY_MAP_DEFAULT_LIMIT = 100;
export const COMMUNITY_MAP_MAX_LIMIT = 200;
export const COMMUTER_REQUEST_TITLE_MAX_LENGTH = 120;
export const COMMUTER_REQUEST_DESCRIPTION_MAX_LENGTH = 500;
export const COMMUTER_REQUEST_BUDGET_MAX_IDR = 10_000_000;
export const COMMUTER_REQUEST_RADIUS_OPTIONS_M = [500, 1000, 2000, 3000] as const;
export const COMMUTER_REQUEST_RADIUS_MIN_M = 100;
export const COMMUTER_REQUEST_RADIUS_MAX_M = 5000;
export const COMMUTER_REQUEST_DEFAULT_RADIUS_M = 1000;
export const COMMUTER_REQUEST_EXPIRY_OPTIONS_DAYS = [1, 3, 7] as const;
export const COMMUTER_REQUEST_DEFAULT_EXPIRY_DAYS = 7;
export const COMMUTER_REQUEST_CATEGORIES = [
  "FOOD",
  "DRINK",
  "DAILY_NEEDS",
  "SERVICE",
  "OTHER_LOCAL_NEED",
] as const;
export const COMMUTER_REQUEST_STATUSES = [
  "ACTIVE",
  "CLOSED",
  "EXPIRED",
] as const;
